#!/usr/bin/python
import sys
import commands
import os
from random import randint
import shutil

extensions = [".ppt"]
if len(sys.argv) != 2:
	print "Uso: convert.py [file ppt o cartella]"
	sys.exit()
arg = sys.argv[1]
if not os.path.exists(arg):
	print "File o cartella non esistente"
	sys.exit()

files = []

arg = os.path.abspath(arg)
if os.path.isdir(arg):
	for i in os.listdir(arg):
		tot = os.path.join(arg, i)
		if os.path.isfile(tot):
			files.append(tot)
elif os.path.isfile(arg):
	files.append(arg)

ppts = []
tmps = []
tmpfolder = "tmp_conv" + str(randint(1, 10000))
newfolder = os.path.join(os.path.dirname(files[0]), tmpfolder)
print newfolder
os.mkdir(newfolder)

for i in files:
	if os.path.splitext(i)[1] in extensions:
		cmd = 'libreoffice --headless --convert-to ppt:"MS PowerPoint 97" --outdir "' + newfolder + '" -env:UserInstallation="file://$HOME/.libreoffice-alt" "' + i + '"'
		print cmd
		os.system(cmd)
		ppts.append(os.path.join(newfolder, os.path.splitext(os.path.basename(i))[0] + ".ppt"))

print len(ppts)
htmls = []
for i in ppts:

	cmd = 'ppthtml "' + i + '"'
	print cmd
	cm = commands.getstatusoutput(cmd)
	out = cm[1].replace('<hr><FONT SIZE=-1>Created with <a href="http://chicago.sf.net/xlhtml">pptHtml</a></FONT><br>', "").decode('utf-8')
	out2 = out.encode('ascii', 'xmlcharrefreplace')
	outpath = os.path.splitext(i)[0] + ".html"
	print outpath
	f = open(outpath, "w")
	f.write(out2)
	f.close()
	htmls.append(outpath)

for i in htmls:
	cmd = 'libreoffice --headless --convert-to doc --outdir "' + os.path.dirname(files[0]) + '" -env:UserInstallation="file://$HOME/.libreoffice-alt" "' + i + '"'
	print cmd
	os.system(cmd)

shutil.rmtree(newfolder)
print "Ok!"
